upstream backend_cluster {
    server backend-node-1:5001 max_fails=1 fail_timeout=5s;
    server backend-node-2:5002 max_fails=1 fail_timeout=5s;
    server backend-python:5003 max_fails=1 fail_timeout=5s;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://backend_cluster;

        # Failover/resiliencia (igual que el taller 1)
        proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
        proxy_next_upstream_timeout 2s;
        proxy_connect_timeout 1s;
        proxy_read_timeout 2s;
        proxy_send_timeout 2s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}